### ISSUE TITLE
Criar o docker com nossa alterações iniciais para disponibilizar a comunidade

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/portal-volto#26]
https://6.docs.plone.org/install/containers/examples/nginx-volto-plone.html

Exemplo de docker-composer.yml

```
version: "3"
services:

  webserver:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.0
    environment:
      SITE: Plone
    volumes:
      - data:/data
    ports:
    - "8080:8080"

volumes:
  data: {}
```
